export var ActionTypes = {
    RECEIVED_AJAX_CALL_FAILURE: 'RECEIVED_AJAX_CALL_FAILURE',
    CHANGE_ORIGIN_CURRENCY: 'CHANGE_ORIGIN_CURRENCY',
    CHANGE_DESTINATION_CURRENCY: 'CHANGE_DESTINATION_CURRENCY',
    CHANGE_ORIGIN_AMOUNT: 'CHANGE_ORIGIN_AMOUNT',
    CHANGE_DESTINATION_AMOUNT: 'CHANGE_DESTINATION_AMOUNT',
    REQUEST_MAKE_FEE: 'REQUEST_MAKE_FEE',
    RECEIVED_MAKE_FEE_SUCCESS: 'RECEIVED_MAKE_FEE_SUCCESS',
    RECEIVED_MAKE_FEE_FAILURE: 'RECEIVED_MAKE_FEE_FAILURE',
    REQUEST_CONVERSION_RATE: 'REQUEST_CONVERSION_RATE',
    RECEIVED_CONVERSION_RATE_SUCCESS: 'RECEIVED_CONVERSION_RATE_SUCCESS',
    RECEIVED_CONVERSION_RATE_FAILURE: 'RECEIVED_CONVERSION_RATE_FAILURE',
}